@echo off
REM ============================================================
REM  install.bat — Install nice!nano v2 (pin-fixed) board into
REM  the Adafruit nRF52 BSP so Arduino IDE 1.8.x can compile.
REM
REM  Run this once after installing or updating the Adafruit
REM  nRF52 Boards package (via Boards Manager).
REM ============================================================

setlocal enabledelayedexpansion

REM --- Locate Adafruit nRF52 platform ---
set "BASE=%LOCALAPPDATA%\Arduino15\packages\adafruit\hardware\nrf52"

if not exist "%BASE%" (
    echo ERROR: Adafruit nRF52 BSP not found at %BASE%
    echo Please install "Adafruit nRF52" from Arduino Boards Manager first.
    pause
    exit /b 1
)

REM --- Find the latest installed version ---
set "LATEST="
for /d %%d in ("%BASE%\*") do set "LATEST=%%d"

if "%LATEST%"=="" (
    echo ERROR: No Adafruit nRF52 version directories found.
    pause
    exit /b 1
)

echo Found Adafruit nRF52 BSP at: %LATEST%

REM --- Determine script directory (where variant files live) ---
set "SCRIPT_DIR=%~dp0"

REM --- Copy variant files ---
set "DEST=%LATEST%\variants\nice_nano_v2_pin_fixed"
echo.
echo Copying variant files to %DEST% ...
if not exist "%DEST%" mkdir "%DEST%"
copy /Y "%SCRIPT_DIR%variants\nice_nano_v2_pin_fixed\variant.h"   "%DEST%\variant.h"   >nul
copy /Y "%SCRIPT_DIR%variants\nice_nano_v2_pin_fixed\variant.cpp" "%DEST%\variant.cpp" >nul
echo   variant.h   OK
echo   variant.cpp OK

REM --- Write boards.local.txt (additive, does not touch boards.txt) ---
set "BOARDS_LOCAL=%LATEST%\boards.local.txt"
echo.
echo Writing %BOARDS_LOCAL% ...

(
echo ##############################################################
echo # nice!nano v2 ^(pin fixed^)
echo #
echo # Auto-generated by install.bat from nicenano-v2-arduino.
echo # Pin mapping follows the physical nice!nano V2 board layout.
echo # D0=P0.08 ^(RX^), D1=P0.06 ^(TX^) — matches the board silkscreen.
echo ##############################################################
echo.
echo nicenanov2pf.name=nice!nano v2 ^(pin fixed^)
echo.
echo nicenanov2pf.vid.0=0x239A
echo nicenanov2pf.pid.0=0x00B3
echo nicenanov2pf.vid.1=0x239A
echo nicenanov2pf.pid.1=0x8029
echo nicenanov2pf.vid.2=0x239A
echo nicenanov2pf.pid.2=0x802A
echo nicenanov2pf.vid.3=0x239A
echo nicenanov2pf.pid.3=0x802B
echo.
echo nicenanov2pf.bootloader.tool=bootburn
echo nicenanov2pf.upload.tool=nrfutil
echo nicenanov2pf.upload.protocol=nrfutil
echo nicenanov2pf.upload.use_1200bps_touch=true
echo nicenanov2pf.upload.wait_for_upload_port=true
echo nicenanov2pf.upload.maximum_size=815104
echo nicenanov2pf.upload.maximum_data_size=237568
echo.
echo nicenanov2pf.build.mcu=cortex-m4
echo nicenanov2pf.build.f_cpu=64000000
echo nicenanov2pf.build.board=nice_nano_v2
echo nicenanov2pf.build.core=nRF5
echo nicenanov2pf.build.variant=nice_nano_v2_pin_fixed
echo nicenanov2pf.build.usb_manufacturer="nice!"
echo nicenanov2pf.build.usb_product="Nice!Nano V2"
echo nicenanov2pf.build.extra_flags=-DNRF52840_XXAA {build.flags.usb}
echo nicenanov2pf.build.ldscript=nrf52840_s140_v6.ld
echo nicenanov2pf.build.openocdscript=scripts/openocd/daplink_nrf52.cfg
echo nicenanov2pf.build.vid=0x239A
echo nicenanov2pf.build.pid=0x8029
echo nicenanov2pf.build.uf2_family=0xADA52840
echo.
echo nicenanov2pf.menu.softdevice.s140v6=S140 6.1.1
echo nicenanov2pf.menu.softdevice.s140v6.build.sd_name=s140
echo nicenanov2pf.menu.softdevice.s140v6.build.sd_version=6.1.1
echo nicenanov2pf.menu.softdevice.s140v6.build.sd_fwid=0x00B6
echo.
echo nicenanov2pf.menu.debug.l0=Level 0 ^(Release^)
echo nicenanov2pf.menu.debug.l0.build.debug_flags=-DCFG_DEBUG=0
echo nicenanov2pf.menu.debug.l1=Level 1 ^(Error Message^)
echo nicenanov2pf.menu.debug.l1.build.debug_flags=-DCFG_DEBUG=1
echo nicenanov2pf.menu.debug.l2=Level 2 ^(Full Debug^)
echo nicenanov2pf.menu.debug.l2.build.debug_flags=-DCFG_DEBUG=2
echo nicenanov2pf.menu.debug.l3=Level 3 ^(Segger SystemView^)
echo nicenanov2pf.menu.debug.l3.build.debug_flags=-DCFG_DEBUG=3
echo nicenanov2pf.menu.debug.l3.build.sysview_flags=-DCFG_SYSVIEW=1
echo.
echo nicenanov2pf.menu.debug_output.serial=Serial
echo nicenanov2pf.menu.debug_output.serial.build.logger_flags=-DCFG_LOGGER=0
echo nicenanov2pf.menu.debug_output.serial1=Serial1
echo nicenanov2pf.menu.debug_output.serial1.build.logger_flags=-DCFG_LOGGER=1 -DCFG_TUSB_DEBUG=CFG_DEBUG
echo nicenanov2pf.menu.debug_output.rtt=Segger RTT
echo nicenanov2pf.menu.debug_output.rtt.build.logger_flags=-DCFG_LOGGER=2 -DCFG_TUSB_DEBUG=CFG_DEBUG -DSEGGER_RTT_MODE_DEFAULT=SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL
) > "%BOARDS_LOCAL%"

echo   boards.local.txt OK
echo.
echo ============================================================
echo  Done! Restart Arduino IDE, then select:
echo    Tools ^> Board ^> Adafruit nRF52 ^> nice!nano v2 ^(pin fixed^)
echo ============================================================
echo.
pause
